import Foundation

class DeveloperPreview{
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo1",
            numberOfBeds: 4,
            pricePerMonth: 3500,
            latitude: 28.6139,
            longitude: 77.2090,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            address: "123 College Rd",
            city: "Delhi",
            state: "Delhi",
            title: "St. Stephen's Hostel",
            rating: 4.9,
            features: [.verified, .mealService],
            amenities: [.wifi, .laundry, .ac, .studyRoom],
            type: .hostel,
            gender: .male,
            reviews: [
                .init(id: NSUUID().uuidString, userId: NSUUID().uuidString, userName: "Amit Kumar", userImageUrl: "male-profile-photo", rating: 5, comment: "Great place to stay!", timestamp: Date()),
                .init(id: NSUUID().uuidString, userId: NSUUID().uuidString, userName: "Priya Sharma", userImageUrl: "male-profile-photo", rating: 4, comment: "Good facilities, but a bit noisy.", timestamp: Date())
            ]
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jane Doe",
            ownerImageUrl: "female-profile-photo1",
            numberOfBeds: 2,
            pricePerMonth: 4200,
            latitude: 19.0760,
            longitude: 72.8777,
            imageURLs: ["listing-5", "listing-6", "listing-7", "listing-8"],
            address: "456 University Ave",
            city: "Mumbai",
            state: "Maharashtra",
            title: "Modern PG for Girls",
            rating: 4.7,
            features: [.verified],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Rajesh Kumar",
            ownerImageUrl: "male-profile-photo2",
            numberOfBeds: 6,
            pricePerMonth: 5600,
            latitude: 12.9716,
            longitude: 77.5946,
            imageURLs: ["listing-9", "listing-10", "listing-11", "listing-1"],
            address: "789 Tech Park Rd",
            city: "Bangalore",
            state: "Karnataka",
            title: "Co-ed Student Hostel",
            rating: 4.5,
            features: [.mealService],
            amenities: [.wifi, .laundry, .studyRoom, .parking],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Priya Patel",
            ownerImageUrl: "female-profile-photo2",
            numberOfBeds: 8,
            pricePerMonth: 6800,
            latitude: 22.5726,
            longitude: 88.3639,
            imageURLs: ["listing-2", "listing-5", "listing-8", "listing-11"],
            address: "101 Park Street",
            city: "Kolkata",
            state: "West Bengal",
            title: "Kolkata Backpackers Hostel",
            rating: 4.6,
            features: [.verified, .mealService],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sanjay Gupta",
            ownerImageUrl: "male-profile-photo3",
            numberOfBeds: 4,
            pricePerMonth: 7200,
            latitude: 17.3850,
            longitude: 78.4867,
            imageURLs: ["listing-3", "listing-6", "listing-9", "listing-1"],
            address: "202 Hitech City Road",
            city: "Hyderabad",
            state: "Telangana",
            title: "Deccan Comforts PG",
            rating: 4.8,
            features: [.verified],
            amenities: [.wifi, .ac, .security, .parking],
            type: .pg,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Anjali Mehta",
            ownerImageUrl: "female-profile-photo3",
            numberOfBeds: 10,
            pricePerMonth: 8100,
            latitude: 26.9124,
            longitude: 75.7873,
            imageURLs: ["listing-4", "listing-7", "listing-10", "listing-2"],
            address: "303 Pink City Lane",
            city: "Jaipur",
            state: "Rajasthan",
            title: "Jaipur Junction Hostel",
            rating: 4.4,
            features: [.mealService],
            amenities: [.wifi, .laundry, .studyRoom],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Vikram Singh",
            ownerImageUrl: "male-profile-photo4",
            numberOfBeds: 3,
            pricePerMonth: 9300,
            latitude: 30.7333,
            longitude: 76.7794,
            imageURLs: ["listing-1", "listing-5", "listing-9", "listing-3"],
            address: "404 Sector 17",
            city: "Chandigarh",
            state: "Chandigarh",
            title: "Chandigarh Boys PG",
            rating: 4.9,
            features: [.verified],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sunita Reddy",
            ownerImageUrl: "female-profile-photo4",
            numberOfBeds: 5,
            pricePerMonth: 4500,
            latitude: 13.0827,
            longitude: 80.2707,
            imageURLs: ["listing-2", "listing-6", "listing-10", "listing-4"],
            address: "505 Marina Beach Road",
            city: "Chennai",
            state: "Tamil Nadu",
            title: "Chennai Central Hostel",
            rating: 4.5,
            features: [.verified, .mealService],
            amenities: [.wifi, .laundry, .ac, .studyRoom],
            type: .hostel,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Amitabh Bannerjee",
            ownerImageUrl: "male-profile-photo5",
            numberOfBeds: 12,
            pricePerMonth: 5800,
            latitude: 25.2744,
            longitude: 82.9739,
            imageURLs: ["listing-3", "listing-7", "listing-11", "listing-5"],
            address: "606 Ghats of Varanasi",
            city: "Varanasi",
            state: "Uttar Pradesh",
            title: "Ganga View Hostel",
            rating: 4.3,
            features: [],
            amenities: [.wifi, .laundry],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Ritu Verma",
            ownerImageUrl: "female-profile-photo5",
            numberOfBeds: 2,
            pricePerMonth: 6300,
            latitude: 28.7041,
            longitude: 77.1025,
            imageURLs: ["listing-4", "listing-8", "listing-1", "listing-6"],
            address: "707 North Campus",
            city: "Delhi",
            state: "Delhi",
            title: "Kamla Nagar Girls PG",
            rating: 4.8,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Arjun Nair",
            ownerImageUrl: "male-profile-photo6",
            numberOfBeds: 8,
            pricePerMonth: 7500,
            latitude: 9.9312,
            longitude: 76.2673,
            imageURLs: ["listing-5", "listing-9", "listing-2", "listing-7"],
            address: "808 Fort Kochi",
            city: "Kochi",
            state: "Kerala",
            title: "Kochi Backpackers Hub",
            rating: 4.7,
            features: [.verified],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Kavita Singh",
            ownerImageUrl: "female-profile-photo6",
            numberOfBeds: 6,
            pricePerMonth: 8800,
            latitude: 18.5204,
            longitude: 73.8567,
            imageURLs: ["listing-6", "listing-10", "listing-3", "listing-8"],
            address: "909 Koregaon Park",
            city: "Pune",
            state: "Maharashtra",
            title: "Pune Student Hostel",
            rating: 4.6,
            features: [.mealService],
            amenities: [.wifi, .laundry, .studyRoom],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Deepak Chopra",
            ownerImageUrl: "male-profile-photo7",
            numberOfBeds: 4,
            pricePerMonth: 3800,
            latitude: 28.6139,
            longitude: 77.2090,
            imageURLs: ["listing-7", "listing-11", "listing-4", "listing-9"],
            address: "1010 Karol Bagh",
            city: "Delhi",
            state: "Delhi",
            title: "Central Delhi Boys PG",
            rating: 4.7,
            features: [.verified],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Meera Desai",
            ownerImageUrl: "female-profile-photo7",
            numberOfBeds: 10,
            pricePerMonth: 4900,
            latitude: 23.0225,
            longitude: 72.5714,
            imageURLs: ["listing-8", "listing-1", "listing-5", "listing-10"],
            address: "1111 Ashram Road",
            city: "Ahmedabad",
            state: "Gujarat",
            title: "Sabarmati Hostel",
            rating: 4.5,
            features: [.mealService],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Rohan Joshi",
            ownerImageUrl: "male-profile-photo1",
            numberOfBeds: 5,
            pricePerMonth: 5200,
            latitude: 19.0760,
            longitude: 72.8777,
            imageURLs: ["listing-9", "listing-2", "listing-6", "listing-11"],
            address: "1212 Bandra West",
            city: "Mumbai",
            state: "Maharashtra",
            title: "Bandra Boys Hostel",
            rating: 4.8,
            features: [.verified],
            amenities: [.wifi, .ac, .security],
            type: .hostel,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sneha Sharma",
            ownerImageUrl: "female-profile-photo8",
            numberOfBeds: 3,
            pricePerMonth: 6500,
            latitude: 12.9716,
            longitude: 77.5946,
            imageURLs: ["listing-10", "listing-3", "listing-7", "listing-1"],
            address: "1313 Koramangala",
            city: "Bangalore",
            state: "Karnataka",
            title: "Koramangala Girls PG",
            rating: 4.9,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Alok Nath",
            ownerImageUrl: "male-profile-photo2",
            numberOfBeds: 15,
            pricePerMonth: 7800,
            latitude: 31.1048,
            longitude: 77.1734,
            imageURLs: ["listing-11", "listing-4", "listing-8", "listing-2"],
            address: "1414 Mall Road",
            city: "Shimla",
            state: "Himachal Pradesh",
            title: "Himalayan Backpackers Hostel",
            rating: 4.2,
            features: [],
            amenities: [.wifi, .laundry],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Natasha Romanoff",
            ownerImageUrl: "female-profile-photo1",
            numberOfBeds: 8,
            pricePerMonth: 9100,
            latitude: 15.2993,
            longitude: 74.1240,
            imageURLs: ["listing-1", "listing-5", "listing-9", "listing-3"],
            address: "1515 Anjuna Beach",
            city: "Goa",
            state: "Goa",
            title: "Goa Beach Hostel",
            rating: 4.7,
            features: [.verified],
            amenities: [.wifi, .ac, .parking],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Rahul Dravid",
            ownerImageUrl: "male-profile-photo3",
            numberOfBeds: 6,
            pricePerMonth: 3300,
            latitude: 12.9716,
            longitude: 77.5946,
            imageURLs: ["listing-2", "listing-6", "listing-10", "listing-4"],
            address: "1616 Indiranagar",
            city: "Bangalore",
            state: "Karnataka",
            title: "Bangalore Boys Hostel",
            rating: 4.8,
            features: [.verified, .mealService],
            amenities: [.wifi, .laundry, .ac, .studyRoom],
            type: .hostel,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Pooja Hegde",
            ownerImageUrl: "female-profile-photo2",
            numberOfBeds: 4,
            pricePerMonth: 4600,
            latitude: 17.3850,
            longitude: 78.4867,
            imageURLs: ["listing-3", "listing-7", "listing-11", "listing-5"],
            address: "1717 Jubilee Hills",
            city: "Hyderabad",
            state: "Telangana",
            title: "Jubilee Hills Girls PG",
            rating: 4.9,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sachin Tendulkar",
            ownerImageUrl: "male-profile-photo4",
            numberOfBeds: 10,
            pricePerMonth: 5900,
            latitude: 19.0760,
            longitude: 72.8777,
            imageURLs: ["listing-4", "listing-8", "listing-1", "listing-6"],
            address: "1818 Dadar",
            city: "Mumbai",
            state: "Maharashtra",
            title: "Mumbai Central Hostel",
            rating: 4.6,
            features: [.mealService],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Anushka Sharma",
            ownerImageUrl: "female-profile-photo3",
            numberOfBeds: 5,
            pricePerMonth: 7100,
            latitude: 28.6139,
            longitude: 77.2090,
            imageURLs: ["listing-5", "listing-9", "listing-2", "listing-7"],
            address: "1919 South Extension",
            city: "Delhi",
            state: "Delhi",
            title: "South Delhi Girls Hostel",
            rating: 4.7,
            features: [.verified],
            amenities: [.wifi, .ac, .security],
            type: .hostel,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Virat Kohli",
            ownerImageUrl: "male-profile-photo5",
            numberOfBeds: 8,
            pricePerMonth: 8400,
            latitude: 30.7333,
            longitude: 76.7794,
            imageURLs: ["listing-6", "listing-10", "listing-3", "listing-8"],
            address: "2020 Elante Mall",
            city: "Chandigarh",
            state: "Chandigarh",
            title: "Chandigarh Backpackers",
            rating: 4.5,
            features: [.verified],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Deepika Padukone",
            ownerImageUrl: "female-profile-photo4",
            numberOfBeds: 3,
            pricePerMonth: 3700,
            latitude: 12.9716,
            longitude: 77.5946,
            imageURLs: ["listing-7", "listing-11", "listing-4", "listing-9"],
            address: "2121 UB City",
            city: "Bangalore",
            state: "Karnataka",
            title: "UB City Luxury PG",
            rating: 5.0,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security, .parking],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Ranveer Singh",
            ownerImageUrl: "male-profile-photo6",
            numberOfBeds: 12,
            pricePerMonth: 5000,
            latitude: 26.9124,
            longitude: 75.7873,
            imageURLs: ["listing-8", "listing-1", "listing-5", "listing-10"],
            address: "2222 Hawa Mahal Road",
            city: "Jaipur",
            state: "Rajasthan",
            title: "Pink City Backpackers",
            rating: 4.4,
            features: [],
            amenities: [.wifi, .laundry],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Alia Bhatt",
            ownerImageUrl: "female-profile-photo5",
            numberOfBeds: 6,
            pricePerMonth: 6200,
            latitude: 18.5204,
            longitude: 73.8567,
            imageURLs: ["listing-9", "listing-2", "listing-6", "listing-11"],
            address: "2323 FC Road",
            city: "Pune",
            state: "Maharashtra",
            title: "Pune Girls Hostel",
            rating: 4.6,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security],
            type: .hostel,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Ranbir Kapoor",
            ownerImageUrl: "male-profile-photo7",
            numberOfBeds: 4,
            pricePerMonth: 7400,
            latitude: 19.0760,
            longitude: 72.8777,
            imageURLs: ["listing-10", "listing-3", "listing-7", "listing-1"],
            address: "2424 Juhu Beach",
            city: "Mumbai",
            state: "Maharashtra",
            title: "Juhu Prime Boys PG",
            rating: 4.8,
            features: [.verified],
            amenities: [.wifi, .ac, .security, .parking],
            type: .pg,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Katrina Kaif",
            ownerImageUrl: "female-profile-photo6",
            numberOfBeds: 8,
            pricePerMonth: 8700,
            latitude: 15.2993,
            longitude: 74.1240,
            imageURLs: ["listing-11", "listing-4", "listing-8", "listing-2"],
            address: "2525 Calangute Beach",
            city: "Goa",
            state: "Goa",
            title: "Goa Fun Hostel",
            rating: 4.7,
            features: [.verified],
            amenities: [.wifi, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Vicky Kaushal",
            ownerImageUrl: "male-profile-photo1",
            numberOfBeds: 10,
            pricePerMonth: 4000,
            latitude: 28.6139,
            longitude: 77.2090,
            imageURLs: ["listing-1", "listing-5", "listing-9", "listing-3"],
            address: "2626 Paharganj",
            city: "Delhi",
            state: "Delhi",
            title: "Delhi Backpackers Inn",
            rating: 4.5,
            features: [.mealService],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Kiara Advani",
            ownerImageUrl: "female-profile-photo7",
            numberOfBeds: 5,
            pricePerMonth: 5300,
            latitude: 17.3850,
            longitude: 78.4867,
            imageURLs: ["listing-2", "listing-6", "listing-10", "listing-4"],
            address: "2727 Banjara Hills",
            city: "Hyderabad",
            state: "Telangana",
            title: "Banjara Hills Girls Hostel",
            rating: 4.8,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security],
            type: .hostel,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sidharth Malhotra",
            ownerImageUrl: "male-profile-photo2",
            numberOfBeds: 6,
            pricePerMonth: 6600,
            latitude: 13.0827,
            longitude: 80.2707,
            imageURLs: ["listing-3", "listing-7", "listing-11", "listing-5"],
            address: "2828 T. Nagar",
            city: "Chennai",
            state: "Tamil Nadu",
            title: "Chennai Boys PG",
            rating: 4.7,
            features: [.verified],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Disha Patani",
            ownerImageUrl: "female-profile-photo8",
            numberOfBeds: 12,
            pricePerMonth: 7900,
            latitude: 22.5726,
            longitude: 88.3639,
            imageURLs: ["listing-4", "listing-8", "listing-1", "listing-6"],
            address: "2929 Salt Lake",
            city: "Kolkata",
            state: "West Bengal",
            title: "Kolkata Travellers Home",
            rating: 4.3,
            features: [],
            amenities: [.wifi, .laundry],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Tiger Shroff",
            ownerImageUrl: "male-profile-photo3",
            numberOfBeds: 8,
            pricePerMonth: 9200,
            latitude: 9.9312,
            longitude: 76.2673,
            imageURLs: ["listing-5", "listing-9", "listing-2", "listing-7"],
            address: "3030 MG Road",
            city: "Kochi",
            state: "Kerala",
            title: "Kochi Waterside Hostel",
            rating: 4.6,
            features: [.verified],
            amenities: [.wifi, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Shraddha Kapoor",
            ownerImageUrl: "female-profile-photo1",
            numberOfBeds: 4,
            pricePerMonth: 3400,
            latitude: 12.9716,
            longitude: 77.5946,
            imageURLs: ["listing-6", "listing-10", "listing-3", "listing-8"],
            address: "3131 Jayanagar",
            city: "Bangalore",
            state: "Karnataka",
            title: "Jayanagar Elite Girls PG",
            rating: 4.9,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Varun Dhawan",
            ownerImageUrl: "male-profile-photo4",
            numberOfBeds: 10,
            pricePerMonth: 4700,
            latitude: 19.0760,
            longitude: 72.8777,
            imageURLs: ["listing-7", "listing-11", "listing-4", "listing-9"],
            address: "3232 Andheri",
            city: "Mumbai",
            state: "Maharashtra",
            title: "Andheri Co-ed Hostel",
            rating: 4.5,
            features: [.mealService],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Kriti Sanon",
            ownerImageUrl: "female-profile-photo2",
            numberOfBeds: 6,
            pricePerMonth: 6000,
            latitude: 28.7041,
            longitude: 77.1025,
            imageURLs: ["listing-8", "listing-1", "listing-5", "listing-10"],
            address: "3333 Hudson Lane",
            city: "Delhi",
            state: "Delhi",
            title: "Hudson Lane Girls Hostel",
            rating: 4.8,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security],
            type: .hostel,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Ayushmann Khurrana",
            ownerImageUrl: "male-profile-photo5",
            numberOfBeds: 8,
            pricePerMonth: 7300,
            latitude: 30.7333,
            longitude: 76.7794,
            imageURLs: ["listing-9", "listing-2", "listing-6", "listing-11"],
            address: "3434 Sector 35",
            city: "Chandigarh",
            state: "Chandigarh",
            title: "Chandigarh Boys Hub",
            rating: 4.7,
            features: [.verified],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Bhumi Pednekar",
            ownerImageUrl: "female-profile-photo3",
            numberOfBeds: 15,
            pricePerMonth: 8600,
            latitude: 25.2744,
            longitude: 82.9739,
            imageURLs: ["listing-10", "listing-3", "listing-7", "listing-1"],
            address: "3535 Assi Ghat",
            city: "Varanasi",
            state: "Uttar Pradesh",
            title: "Varanasi Pilgrim's Hostel",
            rating: 4.2,
            features: [],
            amenities: [.wifi, .laundry],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Rajkummar Rao",
            ownerImageUrl: "male-profile-photo6",
            numberOfBeds: 5,
            pricePerMonth: 3900,
            latitude: 18.5204,
            longitude: 73.8567,
            imageURLs: ["listing-11", "listing-4", "listing-8", "listing-2"],
            address: "3636 Viman Nagar",
            city: "Pune",
            state: "Maharashtra",
            title: "Pune IT Park Hostel",
            rating: 4.6,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .studyRoom],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Taapsee Pannu",
            ownerImageUrl: "female-profile-photo4",
            numberOfBeds: 3,
            pricePerMonth: 5100,
            latitude: 19.0760,
            longitude: 72.8777,
            imageURLs: ["listing-1", "listing-5", "listing-9", "listing-3"],
            address: "3737 Powai",
            city: "Mumbai",
            state: "Maharashtra",
            title: "Powai Lake View PG",
            rating: 4.9,
            features: [.verified],
            amenities: [.wifi, .ac, .security, .parking],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Nawazuddin Siddiqui",
            ownerImageUrl: "male-profile-photo7",
            numberOfBeds: 10,
            pricePerMonth: 6400,
            latitude: 28.6139,
            longitude: 77.2090,
            imageURLs: ["listing-2", "listing-6", "listing-10", "listing-4"],
            address: "3838 Old Delhi",
            city: "Delhi",
            state: "Delhi",
            title: "Old Delhi Charm Hostel",
            rating: 4.4,
            features: [],
            amenities: [.wifi, .laundry],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Radhika Apte",
            ownerImageUrl: "female-profile-photo5",
            numberOfBeds: 6,
            pricePerMonth: 7700,
            latitude: 12.9716,
            longitude: 77.5946,
            imageURLs: ["listing-3", "listing-7", "listing-11", "listing-5"],
            address: "3939 HSR Layout",
            city: "Bangalore",
            state: "Karnataka",
            title: "HSR Layout Co-living",
            rating: 4.7,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Pankaj Tripathi",
            ownerImageUrl: "male-profile-photo1",
            numberOfBeds: 8,
            pricePerMonth: 9000,
            latitude: 26.9124,
            longitude: 75.7873,
            imageURLs: ["listing-4", "listing-8", "listing-1", "listing-6"],
            address: "4040 Amer Fort Road",
            city: "Jaipur",
            state: "Rajasthan",
            title: "Royal Jaipur Hostel",
            rating: 4.5,
            features: [.verified],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sanya Malhotra",
            ownerImageUrl: "female-profile-photo6",
            numberOfBeds: 4,
            pricePerMonth: 4100,
            latitude: 17.3850,
            longitude: 78.4867,
            imageURLs: ["listing-5", "listing-9", "listing-2", "listing-7"],
            address: "4141 Gachibowli",
            city: "Hyderabad",
            state: "Telangana",
            title: "Gachibowli Girls PG",
            rating: 4.8,
            features: [.verified, .mealService],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Manoj Bajpayee",
            ownerImageUrl: "male-profile-photo2",
            numberOfBeds: 12,
            pricePerMonth: 5400,
            latitude: 15.2993,
            longitude: 74.1240,
            imageURLs: ["listing-6", "listing-10", "listing-3", "listing-8"],
            address: "4242 Baga Beach",
            city: "Goa",
            state: "Goa",
            title: "Baga Beach Fun Hostel",
            rating: 4.6,
            features: [],
            amenities: [.wifi, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Fatima Sana Shaikh",
            ownerImageUrl: "female-profile-photo7",
            numberOfBeds: 6,
            pricePerMonth: 6700,
            latitude: 13.0827,
            longitude: 80.2707,
            imageURLs: ["listing-7", "listing-11", "listing-4", "listing-9"],
            address: "4343 Anna Nagar",
            city: "Chennai",
            state: "Tamil Nadu",
            title: "Anna Nagar Girls Hostel",
            rating: 4.7,
            features: [.verified],
            amenities: [.wifi, .ac, .security],
            type: .hostel,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Irrfan Khan",
            ownerImageUrl: "male-profile-photo3",
            numberOfBeds: 8,
            pricePerMonth: 8000,
            latitude: 22.5726,
            longitude: 88.3639,
            imageURLs: ["listing-8", "listing-1", "listing-5", "listing-10"],
            address: "4444 Howrah Bridge",
            city: "Kolkata",
            state: "West Bengal",
            title: "Howrah Bridge View Hostel",
            rating: 4.8,
            features: [.verified],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Kangana Ranaut",
            ownerImageUrl: "female-profile-photo8",
            numberOfBeds: 4,
            pricePerMonth: 8500,
            latitude: 31.1048,
            longitude: 77.1734,
            imageURLs: ["listing-9", "listing-2", "listing-6", "listing-11"],
            address: "4545 Manali",
            city: "Manali",
            state: "Himachal Pradesh",
            title: "Manali Mountain View PG",
            rating: 4.9,
            features: [.verified, .mealService],
            amenities: [.wifi, .parking],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Shahid Kapoor",
            ownerImageUrl: "male-profile-photo4",
            numberOfBeds: 10,
            pricePerMonth: 5700,
            latitude: 9.9312,
            longitude: 76.2673,
            imageURLs: ["listing-10", "listing-3", "listing-7", "listing-1"],
            address: "4646 Marine Drive",
            city: "Kochi",
            state: "Kerala",
            title: "Kochi Marine Hostel",
            rating: 4.6,
            features: [.mealService],
            amenities: [.wifi, .laundry, .ac],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Yami Gautam",
            ownerImageUrl: "female-profile-photo1",
            numberOfBeds: 5,
            pricePerMonth: 6100,
            latitude: 30.7333,
            longitude: 76.7794,
            imageURLs: ["listing-11", "listing-4", "listing-8", "listing-2"],
            address: "4747 Sector 22",
            city: "Chandigarh",
            state: "Chandigarh",
            title: "Chandigarh Girls PG",
            rating: 4.8,
            features: [.verified],
            amenities: [.wifi, .ac, .security],
            type: .pg,
            gender: .female,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sushant Singh Rajput",
            ownerImageUrl: "male-profile-photo5",
            numberOfBeds: 8,
            pricePerMonth: 4300,
            latitude: 18.5204,
            longitude: 73.8567,
            imageURLs: ["listing-1", "listing-5", "listing-9", "listing-3"],
            address: "4848 Hinjewadi",
            city: "Pune",
            state: "Maharashtra",
            title: "Pune Tech Park Hostel",
            rating: 4.7,
            features: [.verified, .mealService],
            amenities: [.wifi, .laundry, .ac, .studyRoom],
            type: .hostel,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jacqueline Fernandez",
            ownerImageUrl: "female-profile-photo2",
            numberOfBeds: 12,
            pricePerMonth: 5500,
            latitude: 19.0760,
            longitude: 72.8777,
            imageURLs: ["listing-2", "listing-6", "listing-10", "listing-4"],
            address: "4949 Colaba",
            city: "Mumbai",
            state: "Maharashtra",
            title: "Mumbai Gateway Hostel",
            rating: 4.5,
            features: [],
            amenities: [.wifi, .laundry],
            type: .hostel,
            gender: .coed,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Abraham",
            ownerImageUrl: "male-profile-photo6",
            numberOfBeds: 6,
            pricePerMonth: 6900,
            latitude: 12.9716,
            longitude: 77.5946,
            imageURLs: ["listing-3", "listing-7", "listing-11", "listing-5"],
            address: "5050 Whitefield",
            city: "Bangalore",
            state: "Karnataka",
            title: "Whitefield Boys Hostel",
            rating: 4.8,
            features: [.verified],
            amenities: [.wifi, .ac, .security, .parking],
            type: .hostel,
            gender: .male,
            reviews: []
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Abraham",
            ownerImageUrl: "male-profile-photo6",
            numberOfBeds: 6,
            pricePerMonth: 6900,
            latitude: 12.9716,
            longitude: 77.5946,
            imageURLs: ["listing-3", "listing-7", "listing-11", "listing-5"],
            address: "5050 Whitefield",
            city: "Bangalore",
            state: "Karnataka",
            title: "Whitefield Boys Hostel",
            rating: 4.8,
            features: [.verified],
            amenities: [.wifi, .ac, .security, .parking],
            type: .hostel,
            gender: .male,
            reviews: []
        )
    ]
}
